services:
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:8002/webhook/
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_HOOK_EVENTS: message.any
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
      - ./waha_sessions:/app/.sessions
      - ./waha_media:/app/.media
    ports:
      - "3000:3000"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_suapia
    ports:
      - "6333:6333" # API REST
      - "6334:6334" # API gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    environment:
      -  ENV_VARIABLE=value

volumes:
  waha_sessions:
  waha_media:
  qdrant_storage:
