services:
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:8002/webhook
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_HOOK_EVENTS: message.any
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
      WAHA_API_KEY: '123456789abcdef' # Valor fictício, substitua pela sua chave real
      WAHA_API_KEY_PLAIN: '123456789abcdef'
    volumes:
      - ./waha_sessions:/app/.sessions
      - ./waha_media:/app/.media
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: vetordatabase
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      # Esta linha mapeia o seu arquivo local para a pasta de inicialização do container
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7-alpine
    container_name: redis_suapia
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  waha_sessions:
  waha_media:
  pgvector_data:
  redis_data:
