version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: vetordatabase
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      # Esta linha mapeia o seu arquivo local para a pasta de inicialização do container
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env # Já configurado com o motor mais leve que recomendei
    volumes:
      - ./waha_data:/app/.waha