version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env # Já configurado com o motor mais leve que recomendei
    volumes:
      - ./waha_data:/app/.waha
